### PR TITLE
Refactor addon and use /config

### PR DESCRIPTION
**Pull request by felipecrs**
If the addon configuration does not provide you enough options, just use your own. There is no shame in that.

Refs https://github.com/vanackej/risco-mqtt-local/issues/1

### CODE REVIEW

**Comment by felipecrs** [comment]
Sorry, I won't be able to work more on this by today.

**Comment by felipecrs** [comment]
@vanackej, I believe the PR is now good to merge now.

**Comment by vanackej** [comment]
Ok, I'll test asap and merge if ok.

Le sam. 5 févr. 2022 à 15:16, Felipe Santos ***@***.***> a
écrit :

**Comment by vanackej** [comment]
Hi,

Just to be sure to understand : How are end users supposed to provide their addon config ?

Because I want them to be able to configure the addon using GUI. My initial issue is that HA config validation is too restrictive and does not support free/values that are required for some of this plugin for customization.

**Comment by pergolafabio** [comment]
Hey, see here :-)

https://github.com/vanackej/risco-mqtt-local/pull/14/commits/0e00bd5bf2f94f2b09f4c141bbb4502f575b5aa4

**Comment by felipecrs** [comment]
Frigate is an example of an addon using the same technique for configuration.

And something that can be made to help users edit/validate their config in VSCode would be a JSON Schema.

**Comment by pergolafabio** [comment]
hey @vanackej , its safe to merge, running it already for few days now :-)

**Comment by pergolafabio** [comment]
Thnx!! :-)

**Pull request merged**
